- name: Lua Busted
  # You may pin to the exact commit or the version.
  # uses: lunarmodules/busted@56e6d68204d1456afa77f1346bf4e050df65b629
  uses: lunarmodules/busted@v2.3.0
  with:
    # Arguments passed to busted
    args: # optional, default is .
